<a href="https://colab.research.google.com/github/mdsarfaraz377/CodeExcercise/blob/master/pyTorchBasics1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU is available
Using GPU: Tesla T4


Creating Tensor

In [3]:
# using empty
a=torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
# zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# torch random
torch.rand(2,3)

tensor([[0.6443, 0.8059, 0.4861],
        [0.9633, 0.3033, 0.6962]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.4691, 0.5319, 0.8878],
        [0.7645, 0.1433, 0.3450]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other way

# arrange
print("using arange ->", torch.arange(0,10,2))

# using linearly space
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3), 5))



using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tesnor Shape

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [13]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    48,     48, 245959],
        [     0,      1,     -1]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [18]:
# find data types
x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([[1,2,3], [4,5,6]], dtype=torch.int64)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operation

#1. Scalar Operation

In [22]:
x=torch.rand([2,2])
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [23]:
# addition
x+2

# subtraction
x-2

# multiplication
x*2

# division
x/2


# integer division
(x*100)//3

# mod
x%3

# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

#2. Element Wise Operation

In [24]:
a = torch.rand([2,3])
b = torch.rand([2,3])

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [25]:
# addition
# a=a+2
# b=b+3
# c=a+b
# print(a)
# print(b)
# print(c)
a+b
# subtraction
a-b
# multiplication
a*b
# division
a/b
# mod
a%b

# power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [26]:
c = torch.tensor([1,-2,3,-4])

In [27]:
c

tensor([ 1, -2,  3, -4])

In [28]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
# floor
torch.floor(c)

tensor([ 1, -2,  3, -4])

In [31]:
# ceil
torch.ceil(c)

tensor([ 1, -2,  3, -4])

In [32]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [33]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [34]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [35]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [36]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

#3. Reduction Operation

In [37]:
e = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [38]:
# sum
total_sum = torch.sum(e)

# sum along columns
total_column_sum = torch.sum(e, dim=0)

# sum along rows
total_row_sum = torch.sum(e, dim=1)

print(total_sum)
print(total_column_sum)
print(total_row_sum)

tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])


In [39]:
# mean
total_mean = torch.mean(e)

# mean along columns
total_col_mean = torch.mean(e, dim=0)

# mean along rows
total_row_mean = torch.mean(e, dim=1)

print(total_mean)
print(total_col_mean)
print(total_row_mean)

tensor(4.)
tensor([4., 0., 8.])
tensor([5., 3.])


In [40]:
# meadian
total_median = torch.median(e)

# median along col
total_col_median = torch.median(e, dim=0)

# median along row
total_row_median = torch.median(e, dim=1)

print("Total median -> ",total_median)
print("Total column median -> ",total_col_median)
print("Total row median -> ",total_row_median)

Total median ->  tensor(0.)
Total column median ->  torch.return_types.median(
values=tensor([0., 0., 7.]),
indices=tensor([1, 0, 0]))
Total row median ->  torch.return_types.median(
values=tensor([7., 0.]),
indices=tensor([2, 1]))


In [41]:
# max and min
total_max = torch.max(e)
print(total_max)

# max along col
total_col_max = torch.max(e,dim=0)
print(total_col_max)

# max along row
total_row_max = torch.max(e,dim=1)
print(total_row_max)

# min
total_min = torch.min(e)
print("Total min ->", total_min)

tensor(9.)
torch.return_types.max(
values=tensor([8., 0., 9.]),
indices=tensor([0, 0, 1]))
torch.return_types.max(
values=tensor([8., 9.]),
indices=tensor([0, 2]))
Total min -> tensor(0.)


In [42]:
# product
total_prod = torch.prod(e)
print(total_prod)

tensor(0.)


In [43]:
# standard deviation
total_std = torch.std(e)
print(total_std)

tensor(4.4272)


In [44]:
# variance
total_var = torch.var(e)
print(total_var)

tensor(19.6000)


In [45]:
# argmax
torch.argmax(e)

tensor(5)

In [46]:
# argmin
torch.argmin(e)

tensor(1)

#4. Matrix Operations

In [47]:
f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g = torch.randint(size=(3,2), low = 0, high = 10, dtype=torch.float32)

print(f)
print(g)

tensor([[5., 7., 3.],
        [9., 4., 0.]])
tensor([[5., 7.],
        [5., 9.],
        [9., 7.]])


In [48]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87., 119.],
        [ 65.,  99.]])

In [51]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [53]:
# transpose
torch.transpose(f,0,1)

tensor([[5., 9.],
        [7., 4.],
        [3., 0.]])

In [57]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 8., 3.],
        [6., 1., 5.],
        [5., 0., 4.]])

In [58]:
# determinant
torch.det(h)

tensor(21.0000)

In [59]:
# inverse
torch.inverse(h)

tensor([[ 0.1905, -1.5238,  1.7619],
        [ 0.0476,  0.6190, -0.8095],
        [-0.2381,  1.9048, -1.9524]])

# Comparison Operations

In [60]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 8, 8],
        [3, 3, 5]])
tensor([[0, 6, 4],
        [0, 8, 4]])


In [66]:
# greater than
i>j

# less than
i<j
# equal to
i=j
# not equal to
i!=j

# greater than equal to
i>=j
# less than equal to
i<=j

tensor([[True, True, True],
        [True, True, True]])

# Special function

In [67]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 2., 3.],
        [8., 5., 6.]])

In [68]:
# log
torch.log(k)

tensor([[1.9459, 0.6931, 1.0986],
        [2.0794, 1.6094, 1.7918]])

In [69]:
# exp
torch.exp(k)

tensor([[1096.6332,    7.3891,   20.0855],
        [2980.9580,  148.4132,  403.4288]])

In [70]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 1.4142, 1.7321],
        [2.8284, 2.2361, 2.4495]])

In [71]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.8808, 0.9526],
        [0.9997, 0.9933, 0.9975]])

In [72]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.2689, 0.0474, 0.0474],
        [0.7311, 0.9526, 0.9526]])

In [73]:
# relu
torch.relu(k)

tensor([[7., 2., 3.],
        [8., 5., 6.]])

# Inplace Operation

In [77]:
m = torch.rand((2,3))
n = torch.rand((2,3))

print(m)
print(n)

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])


In [78]:
m.add_(n)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [79]:
m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [80]:
torch.relu(m)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [81]:
m.relu_()

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [82]:
m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

# Copying a Tensor

In [84]:
a = torch.rand((2,3))
a

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [85]:
b=a

In [86]:
b

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [87]:
a[0][0] = 0

In [88]:
a

tensor([[0.0000, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [89]:
b

tensor([[0.0000, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [90]:
id(a)

139127893788144

In [91]:
id(b)

139127893788144

In [92]:
b = a.clone()

In [93]:
b

tensor([[0.0000, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])